'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
'''

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        counts = [0] * 26  
    
        for ch in t:
            counts[ord(ch) - ord('a')] += 1

        for ch in s:
            counts[ord(ch) - ord('a')] -= 1
        
        for i in range(26):
            if counts[i] > 0:
                return chr(ord('a') + i)
        
        return ' '